<?php
/**
 * BPQDash Visitor Log
 *
 * Logs HTTPS visits to index.php and bpq-rf-connections.html.
 * Include at the top of index.php:
 *   require_once __DIR__ . '/visitor-log.php'; logVisit();
 *
 * For bpq-rf-connections.html, a companion PHP wrapper is used — see bpqdash-rf-log.php.
 *
 * Log file: /var/www/bpqdash/logs/visitor-log.csv
 * Viewer:   https://your-domain.com/visitor-log.php?view=1
 *
 * GeoIP: Uses MaxMind GeoLite2 local database.
 * Install:
 *   sudo apt install php-geoip  (or use Composer: geoip2/geoip2)
 *   Download GeoLite2-City.mmdb from https://dev.maxmind.com/geoip/geolite2-free-geolocation-data
 *   Place at: /var/lib/GeoIP/GeoLite2-City.mmdb
 *
 * To generate the viewer password hash, run on BPQSERVER:
 *   php -r "echo password_hash('LogTprfn2026', PASSWORD_DEFAULT) . PHP_EOL;"
 * Then paste the output into VIEWER_PASSWORD_HASH below.
 */

define('LOG_FILE',             '/var/www/bpqdash/logs/visitor-log.csv');
define('LOG_DIR',              '/var/www/bpqdash/logs');
define('VIEWER_SESSION_TTL',   3600); // seconds — viewer session lifetime
define('GEOIP_DB',             '/var/lib/GeoIP/GeoLite2-City.mmdb');

// Paste hash generated by: php -r "echo password_hash('LogTprfn2026', PASSWORD_DEFAULT) . PHP_EOL;"
define('VIEWER_PASSWORD_HASH', '$2y$10$qA.BvJWR9.SZHDKoi1Kv0u7v/uVTourLQhwzNBWBRd.4zbQ6azFtS');

// ---------------------------------------------------------------------------
// LOGGING FUNCTION — called by index.php and bpqdash-rf-log.php
// ---------------------------------------------------------------------------

/**
 * Look up country and region/state for an IP address using MaxMind GeoLite2.
 * Returns ['country' => 'US', 'region' => 'Georgia'] or empty strings if unavailable.
 */
function geoipLookup(string $ip): array {
    $result = ['country' => '', 'region' => ''];
    if (!file_exists(GEOIP_DB)) return $result;

    // Use geoip2 Reader if Composer autoload is available
    $autoload = '/var/www/bpqdash/vendor/autoload.php';
    if (file_exists($autoload)) {
        try {
            require_once $autoload;
            $reader = new \GeoIp2\Database\Reader(GEOIP_DB);
            $record = $reader->city($ip);
            $result['country'] = $record->country->isoCode ?? '';
            $result['region']  = $record->mostSpecificSubdivision->name ?? '';
            $reader->close();
        } catch (\Exception $e) {
            // IP not found or other error — return empty
        }
        return $result;
    }

    // Fallback: parse mmdb manually via shell mmdbinspect if available
    $mmdbinspect = trim(shell_exec('which mmdbinspect 2>/dev/null') ?? '');
    if ($mmdbinspect) {
        $safe = escapeshellarg($ip);
        $json = shell_exec("$mmdbinspect -db " . escapeshellarg(GEOIP_DB) . " $safe 2>/dev/null");
        if ($json) {
            $data = json_decode($json, true);
            $rec  = $data[0]['Records'][0]['Record'] ?? [];
            $result['country'] = $rec['country']['iso_code'] ?? '';
            $result['region']  = $rec['subdivisions'][0]['names']['en'] ?? '';
        }
    }
    return $result;
}

function logVisit(string $page = '') {
    // Only log HTTPS requests
    $isHttps = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
             || (!empty($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
             || (isset($_SERVER['SERVER_PORT']) && intval($_SERVER['SERVER_PORT']) === 443);

    if (!$isHttps) return;

    // Determine page name
    if ($page === '') {
        $uri = $_SERVER['REQUEST_URI'] ?? '';
        $path = parse_url($uri, PHP_URL_PATH) ?: $uri;
        $page = basename($path);
        if ($page === '' || $page === '/') $page = 'index.php';
    }

    // Only log the two target pages
    $allowed = ['index.php', 'bpq-rf-connections.html', 'bpqdash-rf-log.php', 'bpqdash-index-log.php', 'bpqdash-network-map'];
    if (!in_array($page, $allowed, true)) return;

    // Resolve real page name for wrappers
    if ($page === 'bpqdash-rf-log.php') $page = 'bpq-rf-connections.html';
    if ($page === 'bpqdash-index-log.php') $page = 'bpqdash-network-map';

    // Collect visitor info
    $timestamp = gmdate('Y-m-d H:i:s') . ' UTC';
    $ip        = getClientIp();
    $ua        = substr($_SERVER['HTTP_USER_AGENT'] ?? 'unknown', 0, 200);

    // Ensure log directory and file exist
    if (!is_dir(LOG_DIR)) {
        @mkdir(LOG_DIR, 0750, true);
    }
    if (!file_exists(LOG_FILE)) {
        @file_put_contents(LOG_FILE, "timestamp,ip,country,region,page,user_agent\n");
        @chmod(LOG_FILE, 0640);
    }

    // GeoIP lookup (gracefully skipped if DB not installed)
    $geo = geoipLookup($ip);

    // Append CSV row (fields quoted to handle commas in UA strings)
    $row = implode(',', [
        '"' . $timestamp . '"',
        '"' . $ip . '"',
        '"' . str_replace('"', '""', $geo['country']) . '"',
        '"' . str_replace('"', '""', $geo['region'])  . '"',
        '"' . $page . '"',
        '"' . str_replace('"', '""', $ua) . '"',
    ]) . "\n";

    @file_put_contents(LOG_FILE, $row, FILE_APPEND | LOCK_EX);
}

function getClientIp(): string {
    // Respect X-Forwarded-For if set by a trusted proxy (nginx)
    if (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
        $ips = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);
        return trim($ips[0]);
    }
    return $_SERVER['REMOTE_ADDR'] ?? 'unknown';
}

// ---------------------------------------------------------------------------
// VIEWER — only runs when ?view=1 is in the query string
// ---------------------------------------------------------------------------

if (isset($_GET['view'])) {

    // --- AUTH (cookie-based, no PHP sessions required) ---
    $cookieName  = 'vlog_auth';
    $cookieToken = hash_hmac('sha256', 'vlog_authenticated', VIEWER_PASSWORD_HASH);

    if (isset($_POST['password'])) {
        if (VIEWER_PASSWORD_HASH === '%%VIEWER_HASH%%') {
            http_response_code(500);
            die('<pre>Viewer password hash not configured. Run on BPQSERVER:
  php -r "echo password_hash(\'LogTprfn2026\', PASSWORD_DEFAULT) . PHP_EOL;"
Then paste the output into visitor-log.php as VIEWER_PASSWORD_HASH.</pre>');
        }
        if (password_verify($_POST['password'], VIEWER_PASSWORD_HASH)) {
            setcookie($cookieName, $cookieToken, [
                'expires'  => time() + VIEWER_SESSION_TTL,
                'path'     => '/',
                'secure'   => true,
                'httponly' => true,
                'samesite' => 'Strict',
            ]);
            header('Location: ?view=1');
            exit;
        } else {
            $loginError = 'Incorrect password.';
        }
    }

    if (isset($_POST['logout'])) {
        setcookie($cookieName, '', ['expires' => time() - 3600, 'path' => '/', 'secure' => true, 'httponly' => true]);
        header('Location: ?view=1');
        exit;
    }

    $authed = isset($_COOKIE[$cookieName])
           && hash_equals($cookieToken, $_COOKIE[$cookieName]);

    // --- RENDER ---
    header('Content-Type: text/html; charset=utf-8');
    ?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>BPQDash Visitor Log</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #0f172a; color: #e2e8f0; min-height: 100vh; }
  .header { background: #1e3a5f; padding: 16px 24px; display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid #2d6aab; }
  .header h1 { font-size: 1.2rem; font-weight: 700; color: #93c5fd; letter-spacing: 0.05em; }
  .header .sub { font-size: 0.75rem; color: #94a3b8; margin-top: 2px; }
  .content { padding: 24px; max-width: 1400px; margin: 0 auto; }
  .login-box { max-width: 340px; margin: 80px auto; background: #1e293b; border: 1px solid #334155; border-radius: 10px; padding: 32px; }
  .login-box h2 { font-size: 1rem; color: #93c5fd; margin-bottom: 20px; }
  .login-box input[type=password] { width: 100%; padding: 9px 12px; background: #0f172a; border: 1px solid #334155; border-radius: 6px; color: #e2e8f0; font-size: 0.9rem; margin-bottom: 12px; }
  .login-box button { width: 100%; padding: 9px; background: #2563eb; color: white; border: none; border-radius: 6px; font-weight: 600; cursor: pointer; font-size: 0.9rem; }
  .login-box button:hover { background: #1d4ed8; }
  .error { color: #f87171; font-size: 0.85rem; margin-bottom: 10px; }
  .stats { display: flex; gap: 16px; margin-bottom: 20px; flex-wrap: wrap; }
  .stat { background: #1e293b; border: 1px solid #334155; border-radius: 8px; padding: 14px 20px; min-width: 140px; }
  .stat .val { font-size: 1.6rem; font-weight: 700; color: #60a5fa; }
  .stat .lbl { font-size: 0.75rem; color: #94a3b8; margin-top: 2px; }
  .filters { display: flex; gap: 10px; margin-bottom: 16px; flex-wrap: wrap; align-items: center; }
  .filters input, .filters select { padding: 7px 10px; background: #1e293b; border: 1px solid #334155; border-radius: 6px; color: #e2e8f0; font-size: 0.85rem; }
  .filters input { width: 200px; }
  .filters button { padding: 7px 14px; background: #334155; color: #e2e8f0; border: 1px solid #475569; border-radius: 6px; cursor: pointer; font-size: 0.85rem; }
  .filters button:hover { background: #475569; }
  .filters .logout-btn { margin-left: auto; background: #7f1d1d; border-color: #991b1b; color: #fca5a5; }
  .filters .logout-btn:hover { background: #991b1b; }
  table { width: 100%; border-collapse: collapse; font-size: 0.82rem; }
  thead tr { background: #1e3a5f; }
  thead th { padding: 10px 12px; text-align: left; color: #93c5fd; font-weight: 600; white-space: nowrap; cursor: pointer; user-select: none; }
  thead th:hover { background: #1e4a7f; }
  thead th .sort-arrow { margin-left: 4px; opacity: 0.5; }
  thead th.sorted .sort-arrow { opacity: 1; color: #60a5fa; }
  tbody tr { border-bottom: 1px solid #1e293b; }
  tbody tr:hover { background: #1e293b; }
  td { padding: 8px 12px; color: #cbd5e1; vertical-align: top; }
  td.ts { white-space: nowrap; color: #94a3b8; font-size: 0.78rem; }
  td.ip { font-family: monospace; color: #86efac; white-space: nowrap; }
  td.page span { display: inline-block; padding: 2px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: 600; }
  td.page span.index { background: #1e3a5f; color: #93c5fd; }
  td.page span.rf { background: #1c3a2a; color: #6ee7b7; }
  td.geo { white-space: nowrap; font-size: 0.82rem; }
  td.ua { color: #94a3b8; font-size: 0.75rem; max-width: 400px; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
  .empty { text-align: center; color: #475569; padding: 48px; font-size: 0.9rem; }
  .table-wrap { overflow-x: auto; background: #0f172a; border: 1px solid #1e293b; border-radius: 8px; }
  .pager { display: flex; gap: 8px; align-items: center; margin-top: 14px; flex-wrap: wrap; }
  .pager button { padding: 5px 12px; background: #1e293b; border: 1px solid #334155; border-radius: 5px; color: #e2e8f0; cursor: pointer; font-size: 0.82rem; }
  .pager button:hover { background: #334155; }
  .pager button.active { background: #2563eb; border-color: #2563eb; }
  .pager .info { color: #64748b; font-size: 0.82rem; margin-left: 8px; }
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="h1">📋 BPQDash Visitor Log</div>
    <div class="sub">your-domain.com — index.php &amp; bpq-rf-connections.html</div>
  </div>
  <?php if ($authed): ?>
  <form method="post" style="margin:0">
    <button class="filters logout-btn" name="logout" value="1" style="padding:6px 14px;border-radius:6px;cursor:pointer;font-size:0.82rem;background:#7f1d1d;border:1px solid #991b1b;color:#fca5a5;">Sign Out</button>
  </form>
  <?php endif; ?>
</div>

<div class="content">
<?php if (!$authed): ?>
  <div class="login-box">
    <h2>🔒 Viewer Login</h2>
    <?php if (!empty($loginError)): ?>
      <div class="error"><?= htmlspecialchars($loginError) ?></div>
    <?php endif; ?>
    <form method="post">
      <input type="password" name="password" placeholder="Password" autofocus>
      <button type="submit">Sign In</button>
    </form>
  </div>
<?php else:
    // --- LOAD AND PARSE LOG ---
    $rows = [];
    if (file_exists(LOG_FILE)) {
        $handle = fopen(LOG_FILE, 'r');
        $header = fgetcsv($handle); // skip header
        while (($row = fgetcsv($handle)) !== false) {
            if (count($row) >= 4) {
                // Support both old format (4 cols) and new format (6 cols with geo)
                if (count($row) >= 6) {
                    $rows[] = [
                        'ts'      => $row[0],
                        'ip'      => $row[1],
                        'country' => $row[2],
                        'region'  => $row[3],
                        'page'    => $row[4],
                        'ua'      => $row[5],
                    ];
                } else {
                    $rows[] = [
                        'ts'      => $row[0],
                        'ip'      => $row[1],
                        'country' => '',
                        'region'  => '',
                        'page'    => $row[2],
                        'ua'      => $row[3],
                    ];
                }
            }
        }
        fclose($handle);
    }
    $rows = array_reverse($rows); // newest first

    // --- FILTER ---
    $filterIp      = trim($_GET['ip']      ?? '');
    $filterPage    = trim($_GET['page']    ?? '');
    $filterUa      = trim($_GET['ua']      ?? '');
    $filterCountry = trim($_GET['country'] ?? '');

    $filtered = array_filter($rows, function($r) use ($filterIp, $filterPage, $filterUa, $filterCountry) {
        if ($filterIp      && stripos($r['ip'],      $filterIp)      === false) return false;
        if ($filterPage    && $r['page'] !== $filterPage)                        return false;
        if ($filterUa      && stripos($r['ua'],      $filterUa)      === false) return false;
        if ($filterCountry && stripos($r['country'], $filterCountry) === false) return false;
        return true;
    });
    $filtered = array_values($filtered);

    // --- STATS ---
    $totalAll       = count($rows);
    $totalFilter    = count($filtered);
    $uniqueIps      = count(array_unique(array_column($filtered, 'ip')));
    $uniqueCountries = count(array_filter(array_unique(array_column($filtered, 'country'))));
    $indexCount     = count(array_filter($filtered, fn($r) => $r['page'] === 'index.php'));
    $rfCount        = count(array_filter($filtered, fn($r) => $r['page'] === 'bpq-rf-connections.html'));

    // Build country list for filter dropdown (sorted by visit count)
    $countryCounts = array_count_values(array_filter(array_column($rows, 'country')));
    arsort($countryCounts);

    // --- PAGINATION ---
    $perPage     = 100;
    $totalPages  = max(1, (int)ceil($totalFilter / $perPage));
    $currentPage = max(1, min($totalPages, (int)($_GET['p'] ?? 1)));
    $offset      = ($currentPage - 1) * $perPage;
    $pageRows    = array_slice($filtered, $offset, $perPage);

    $qBase = http_build_query(array_filter([
        'view'    => '1',
        'ip'      => $filterIp,
        'page'    => $filterPage,
        'ua'      => $filterUa,
        'country' => $filterCountry,
    ]));
?>

  <div class="stats">
    <div class="stat"><div class="val"><?= number_format($totalAll) ?></div><div class="lbl">Total Visits</div></div>
    <div class="stat"><div class="val"><?= number_format($uniqueIps) ?></div><div class="lbl">Unique IPs<?= $filterIp || $filterPage || $filterUa || $filterCountry ? ' (filtered)' : '' ?></div></div>
    <div class="stat"><div class="val"><?= number_format($uniqueCountries) ?></div><div class="lbl">Countries<?= $filterCountry ? ' (filtered)' : '' ?></div></div>
    <div class="stat"><div class="val"><?= number_format($indexCount) ?></div><div class="lbl">index.php</div></div>
    <div class="stat"><div class="val"><?= number_format($rfCount) ?></div><div class="lbl">rf-connections</div></div>
  </div>

  <form method="get" style="margin:0">
    <input type="hidden" name="view" value="1">
    <div class="filters">
      <input type="text" name="ip"   placeholder="Filter by IP…"    value="<?= htmlspecialchars($filterIp) ?>">
      <select name="page">
        <option value="">All pages</option>
        <option value="index.php"          <?= $filterPage === 'index.php'          ? 'selected' : '' ?>>index.php</option>
        <option value="bpq-rf-connections.html"<?= $filterPage === 'bpq-rf-connections.html'? 'selected' : '' ?>>bpq-rf-connections.html</option>
      </select>
      <input type="text" name="ua"   placeholder="Filter by browser…" value="<?= htmlspecialchars($filterUa) ?>">
      <select name="country">
        <option value="">All countries</option>
        <?php foreach ($countryCounts as $cc => $cnt): ?>
        <option value="<?= htmlspecialchars($cc) ?>" <?= $filterCountry === $cc ? 'selected' : '' ?>><?= htmlspecialchars($cc) ?> (<?= $cnt ?>)</option>
        <?php endforeach; ?>
      </select>
      <input type="hidden" name="p" value="1">
      <button type="submit">Apply</button>
      <a href="?view=1" style="padding:7px 14px;background:#334155;color:#e2e8f0;border:1px solid #475569;border-radius:6px;font-size:0.85rem;text-decoration:none;">Clear</a>
      <a href="<?= LOG_FILE ?>" download style="padding:7px 14px;background:#1e3a5f;color:#93c5fd;border:1px solid #2d6aab;border-radius:6px;font-size:0.85rem;text-decoration:none;" onclick="return confirmDownload()">⬇ Download CSV</a>
    </div>
  </form>

  <?php if (empty($pageRows)): ?>
    <div class="empty">No log entries found<?= $filterIp || $filterPage || $filterUa ? ' matching filters' : ' yet' ?>.</div>
  <?php else: ?>
  <div class="table-wrap">
    <table id="logTable">
      <thead>
        <tr>
          <th>Timestamp (UTC)</th>
          <th>IP Address</th>
          <th>Country</th>
          <th>Region / State</th>
          <th>Page</th>
          <th>User Agent</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($pageRows as $r): ?>
        <tr>
          <td class="ts"><?= htmlspecialchars($r['ts']) ?></td>
          <td class="ip">
            <a href="?view=1&ip=<?= urlencode($r['ip']) ?>" style="color:inherit;text-decoration:none;" title="Filter by this IP"><?= htmlspecialchars($r['ip']) ?></a>
          </td>
          <td class="geo">
            <?php if ($r['country']): ?>
              <a href="?view=1&country=<?= urlencode($r['country']) ?>" style="color:#fcd34d;text-decoration:none;font-weight:600;" title="Filter by <?= htmlspecialchars($r['country']) ?>"><?= htmlspecialchars($r['country']) ?></a>
            <?php else: ?>
              <span style="color:#475569;">—</span>
            <?php endif; ?>
          </td>
          <td class="geo" style="color:#94a3b8;"><?= htmlspecialchars($r['region'] ?: '—') ?></td>
          <td class="page">
            <?php if ($r['page'] === 'index.php'): ?>
              <span class="index">index.php</span>
            <?php else: ?>
              <span class="rf">rf-connections</span>
            <?php endif; ?>
          </td>
          <td class="ua" title="<?= htmlspecialchars($r['ua']) ?>"><?= htmlspecialchars($r['ua']) ?></td>
        </tr>
        <?php endforeach; ?>
      </tbody>
    </table>
  </div>

  <div class="pager">
    <?php if ($totalPages > 1): ?>
      <?php if ($currentPage > 1): ?>
        <a href="?<?= $qBase ?>&p=<?= $currentPage - 1 ?>"><button>← Prev</button></a>
      <?php endif; ?>
      <?php
        $start = max(1, $currentPage - 3);
        $end   = min($totalPages, $currentPage + 3);
        for ($i = $start; $i <= $end; $i++):
      ?>
        <a href="?<?= $qBase ?>&p=<?= $i ?>"><button class="<?= $i === $currentPage ? 'active' : '' ?>"><?= $i ?></button></a>
      <?php endfor; ?>
      <?php if ($currentPage < $totalPages): ?>
        <a href="?<?= $qBase ?>&p=<?= $currentPage + 1 ?>"><button>Next →</button></a>
      <?php endif; ?>
    <?php endif; ?>
    <span class="info">
      Showing <?= number_format($offset + 1) ?>–<?= number_format(min($offset + $perPage, $totalFilter)) ?>
      of <?= number_format($totalFilter) ?> entries
      <?= $totalFilter < $totalAll ? '(filtered from ' . number_format($totalAll) . ' total)' : '' ?>
    </span>
  </div>
  <?php endif; ?>

<?php endif; ?>
</div>
<script>
function confirmDownload() {
    return confirm('Download the raw visitor-log.csv file?');
}
</script>
</body>
</html>
<?php
    exit;
}
// If ?view=1 is not set and this file is included, logVisit() is available but nothing else runs.
